"""Declarative MongoDB prompt cases for the LangGraph route tests."""

from __future__ import annotations

MONGODB_PROMPT_CASES = [
    {
        "name": "mongo_projection_emails",
        "question": "show user emails",
        "expected": "success",
        "selection": {"collections": ["users"]},
        "plan": {
            "operation": "find",
            "collection": "users",
            "intent": "",
            "match": {},
            "project": {"email": 1},
            "sort": {},
            "limit": 10,
        },
        "query_fragments": ['"$project"', '"email": 1'],
        "rows": [
            {"email": "alice@example.com"},
            {"email": "bob@example.com"},
            {"email": "charlie@example.com"},
        ],
        "row_count": 3,
    },
    {
        "name": "mongo_count_users",
        "question": "how many users",
        "expected": "success",
        "selection": {"collections": ["users"]},
        "plan": {
            "operation": "aggregate",
            "collection": "users",
            "intent": "count",
            "match": {},
            "project": {},
            "sort": {},
            "limit": 10,
        },
        "query_fragments": ['"$count": "count"'],
        "rows": [{"count": 3}],
        "row_count": 1,
    },
    {
        "name": "mongo_projection_verbose_emails",
        "question": "could you please list the email addresses for every user in the system",
        "expected": "success",
        "selection": {"collections": ["users"]},
        "plan": {
            "operation": "find",
            "collection": "users",
            "intent": "",
            "match": {},
            "project": {"email": 1},
            "sort": {},
            "group_by": [],
            "aggregations": [],
            "limit": 10,
        },
        "query_fragments": ['"$project"', '"email": 1'],
        "rows": [
            {"email": "alice@example.com"},
            {"email": "bob@example.com"},
            {"email": "charlie@example.com"},
        ],
        "row_count": 3,
    },
    {
        "name": "mongo_ends_with",
        "question": "user with name ending with b",
        "expected": "success",
        "selection": {"collections": ["users"]},
        "plan": {
            "operation": "find",
            "collection": "users",
            "intent": "",
            "match": {
                "name": {"$regex": "b$", "$options": "i"},
            },
            "project": {"name": 1},
            "sort": {},
            "limit": 10,
        },
        "query_fragments": ['"name"', '"$regex": "b$"'],
        "rows": [{"name": "Bob"}],
        "row_count": 1,
    },
    {
        "name": "mongo_cross_field_or",
        "question": "show users where name contains alice or email contains bob",
        "expected": "success",
        "selection": {"collections": ["users"]},
        "plan": {
            "operation": "find",
            "collection": "users",
            "intent": "",
            "match": {
                "$or": [
                    {"name": {"$regex": "alice", "$options": "i"}},
                    {"email": {"$regex": "bob", "$options": "i"}},
                ]
            },
            "project": {"name": 1, "email": 1},
            "sort": {},
            "limit": 10,
        },
        "query_fragments": ['"$or"', '"name"', '"email"'],
        "rows": [
            {"name": "Alice", "email": "alice@example.com"},
            {"name": "Bob", "email": "bob@example.com"},
        ],
        "row_count": 2,
    },
    {
        "name": "mongo_top_two_sorted_users",
        "question": "show top 2 users ordered by name",
        "expected": "success",
        "selection": {"collections": ["users"]},
        "plan": {
            "operation": "find",
            "collection": "users",
            "intent": "",
            "match": {},
            "project": {"name": 1, "email": 1},
            "sort": {"name": 1},
            "group_by": [],
            "aggregations": [],
            "limit": 2,
        },
        "query_fragments": ['"$sort"', '"name": 1', '"$limit": 2'],
        "rows": [
            {"name": "Alice", "email": "alice@example.com"},
            {"name": "Bob", "email": "bob@example.com"},
        ],
        "row_count": 2,
    },
    {
        "name": "mongo_numeric_comparison_orders",
        "question": "show orders where amount is at least 100",
        "expected": "success",
        "selection": {"collections": ["orders"]},
        "plan": {
            "operation": "find",
            "collection": "orders",
            "intent": "",
            "match": {
                "amount": {"$gte": 100},
            },
            "project": {"user_name": 1, "amount": 1},
            "sort": {"amount": 1},
            "group_by": [],
            "aggregations": [],
            "limit": 10,
        },
        "query_fragments": ['"$gte": 100', '"amount": 1'],
        "rows": [
            {"user_name": "Alice", "amount": 120.5},
            {"user_name": "Alice", "amount": 300.0},
        ],
        "row_count": 2,
    },
    {
        "name": "mongo_count_users_by_status",
        "question": "count users by status",
        "expected": "success",
        "selection": {"collections": ["users"]},
        "plan": {
            "operation": "aggregate",
            "collection": "users",
            "intent": "group",
            "match": {},
            "project": {},
            "sort": {"status": 1},
            "group_by": ["status"],
            "aggregations": [
                {"function": "COUNT", "field": "*", "alias": "count"},
            ],
            "limit": 10,
        },
        "query_fragments": ['"$group"', '"$sum": 1'],
        "rows": [
            {"status": "active", "count": 2.0},
            {"status": "inactive", "count": 1.0},
        ],
        "row_count": 2,
    },
    {
        "name": "mongo_average_order_amount_by_user",
        "question": "average order amount by user name",
        "expected": "success",
        "selection": {"collections": ["orders"]},
        "plan": {
            "operation": "aggregate",
            "collection": "orders",
            "intent": "group",
            "match": {},
            "project": {},
            "sort": {"user_name": 1},
            "group_by": ["user_name"],
            "aggregations": [
                {"function": "AVG", "field": "amount", "alias": "avg_amount"},
            ],
            "limit": 10,
        },
        "query_fragments": ['"$group"', '"$avg": "$amount"'],
        "rows": [
            {"user_name": "Alice", "avg_amount": 210.25},
            {"user_name": "Bob", "avg_amount": 60.0},
            {"user_name": "Charlie", "avg_amount": 90.0},
        ],
        "row_count": 3,
    },
    {
        "name": "mongo_not_contains_email",
        "question": "show users where email does not contain bob",
        "expected": "success",
        "selection": {"collections": ["users"]},
        "plan": {
            "operation": "find",
            "collection": "users",
            "intent": "",
            "match": {
                "email": {"$not": {"$regex": "bob", "$options": "i"}},
            },
            "project": {"name": 1, "email": 1},
            "sort": {"name": 1},
            "group_by": [],
            "aggregations": [],
            "limit": 10,
        },
        "query_fragments": ['"$not"', '"$regex": "bob"'],
        "rows": [
            {"name": "Alice", "email": "alice@example.com"},
            {"name": "Charlie", "email": "charlie@example.com"},
        ],
        "row_count": 2,
    },
    {
        "name": "mongo_combined_active_users",
        "question": "show active users where email contains example.com",
        "expected": "success",
        "selection": {"collections": ["users"]},
        "plan": {
            "operation": "find",
            "collection": "users",
            "intent": "",
            "match": {
                "status": "active",
                "email": {"$regex": "example.com", "$options": "i"},
            },
            "project": {"name": 1, "email": 1, "status": 1},
            "sort": {"name": 1},
            "group_by": [],
            "aggregations": [],
            "limit": 10,
        },
        "query_fragments": ['"status": "active"', '"$regex": "example.com"'],
        "rows": [
            {"name": "Alice", "email": "alice@example.com", "status": "active"},
            {"name": "Bob", "email": "bob@example.com", "status": "active"},
        ],
        "row_count": 2,
    },
    {
        "name": "mongo_destructive_block",
        "question": "delete all users",
        "expected": "error",
        "selection": {"collections": ["users"]},
        "plan": {"error": "Only read-only queries are allowed."},
    },
]
