"""Declarative SQL prompt cases used by the LangGraph route tests."""

from __future__ import annotations

SQL_PROMPT_CASES = [
    {
        "name": "projection_emails",
        "question": "show user emails",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["users"],
            "fields": ["users.email"],
            "filters": [],
            "joins": [],
            "aggregations": [],
            "group_by": [],
            "order_by": [],
            "limit": 10,
        },
        "sql_fragments": ["SELECT users.email FROM users", "LIMIT 10"],
        "rows": [
            {"email": "alice@example.com"},
            {"email": "bob@example.com"},
            {"email": "charlie@example.com"},
        ],
        "row_count": 3,
    },
    {
        "name": "projection_top_two",
        "question": "show top 2 user emails",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["users"],
            "fields": ["users.email"],
            "filters": [],
            "joins": [],
            "aggregations": [],
            "group_by": [],
            "order_by": [],
            "limit": 2,
        },
        "sql_fragments": ["SELECT users.email FROM users", "LIMIT 2"],
        "rows": [
            {"email": "alice@example.com"},
            {"email": "bob@example.com"},
        ],
        "row_count": 2,
    },
    {
        "name": "projection_verbose_emails",
        "question": "could you please list the email addresses for every user in the system",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["users"],
            "fields": ["users.email"],
            "filters": [],
            "joins": [],
            "aggregations": [],
            "group_by": [],
            "order_by": [],
            "limit": 10,
        },
        "sql_fragments": ["SELECT users.email FROM users", "LIMIT 10"],
        "rows": [
            {"email": "alice@example.com"},
            {"email": "bob@example.com"},
            {"email": "charlie@example.com"},
        ],
        "row_count": 3,
    },
    {
        "name": "count_users",
        "question": "how many users",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["users"],
            "fields": [],
            "filters": [],
            "joins": [],
            "aggregations": [{"function": "COUNT", "field": "*", "alias": "count"}],
            "group_by": [],
            "order_by": [],
            "limit": 10,
        },
        "sql_fragments": ["SELECT COUNT(*) AS count FROM users"],
        "rows": [{"count": 3}],
        "row_count": 1,
    },
    {
        "name": "contains_any",
        "question": "user with name containing any one letter b,z",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["users"],
            "fields": ["users.name"],
            "filters": [
                {"field": "users.name", "operator": "CONTAINS_ANY", "value": ["b", "z"]},
            ],
            "joins": [],
            "aggregations": [],
            "group_by": [],
            "order_by": [],
            "limit": 10,
        },
        "sql_fragments": ["LOWER(users.name)", "LIKE '%b%'", "OR", "LIKE '%z%'"],
        "rows": [{"name": "Bob"}],
        "row_count": 1,
    },
    {
        "name": "ends_with",
        "question": "user with name ending with b",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["users"],
            "fields": ["users.name"],
            "filters": [
                {"field": "users.name", "operator": "ENDS_WITH", "value": "b"},
            ],
            "joins": [],
            "aggregations": [],
            "group_by": [],
            "order_by": [],
            "limit": 10,
        },
        "sql_fragments": ["LOWER(users.name)", "LIKE '%b'"],
        "rows": [{"name": "Bob"}],
        "row_count": 1,
    },
    {
        "name": "exact_match",
        "question": "name is Alice",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["users"],
            "fields": ["users.name", "users.email"],
            "filters": [
                {"field": "users.name", "operator": "=", "value": "Alice"},
            ],
            "joins": [],
            "aggregations": [],
            "group_by": [],
            "order_by": [],
            "limit": 10,
        },
        "sql_fragments": ["users.name = 'Alice'"],
        "rows": [{"name": "Alice", "email": "alice@example.com"}],
        "row_count": 1,
    },
    {
        "name": "negation",
        "question": "name is not Alice",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["users"],
            "fields": ["users.name"],
            "filters": [
                {"field": "users.name", "operator": "!=", "value": "Alice"},
            ],
            "joins": [],
            "aggregations": [],
            "group_by": [],
            "order_by": [{"field": "users.name", "direction": "ASC"}],
            "limit": 10,
        },
        "sql_fragments": ["users.name <> 'Alice'"],
        "rows": [{"name": "Bob"}, {"name": "Charlie"}],
        "row_count": 2,
    },
    {
        "name": "numeric_comparison",
        "question": "show orders where amount >= 100",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["orders"],
            "fields": ["orders.amount"],
            "filters": [
                {"field": "orders.amount", "operator": ">=", "value": 100},
            ],
            "joins": [],
            "aggregations": [],
            "group_by": [],
            "order_by": [{"field": "orders.amount", "direction": "ASC"}],
            "limit": 10,
        },
        "sql_fragments": ["orders.amount >= 100"],
        "rows": [{"amount": 120.5}, {"amount": 300.0}],
        "row_count": 2,
    },
    {
        "name": "numeric_comparison_verbose",
        "question": "show me any orders where the amount is at least 100",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["orders"],
            "fields": ["orders.amount"],
            "filters": [
                {"field": "orders.amount", "operator": ">=", "value": 100},
            ],
            "joins": [],
            "aggregations": [],
            "group_by": [],
            "order_by": [{"field": "orders.amount", "direction": "ASC"}],
            "limit": 10,
        },
        "sql_fragments": ["orders.amount >= 100"],
        "rows": [{"amount": 120.5}, {"amount": 300.0}],
        "row_count": 2,
    },
    {
        "name": "combined_and",
        "question": "show users where name contains alice and email contains example.com",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["users"],
            "fields": ["users.name", "users.email"],
            "filters": [
                {"field": "users.name", "operator": "CONTAINS", "value": "alice"},
                {
                    "field": "users.email",
                    "operator": "CONTAINS",
                    "value": "example.com",
                    "combine_with_previous": "AND",
                },
            ],
            "joins": [],
            "aggregations": [],
            "group_by": [],
            "order_by": [],
            "limit": 10,
        },
        "sql_fragments": ["LOWER(users.name)", "AND", "LOWER(users.email)"],
        "rows": [{"name": "Alice", "email": "alice@example.com"}],
        "row_count": 1,
    },
    {
        "name": "cross_field_or",
        "question": "show users where name contains alice or email contains bob",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["users"],
            "fields": ["users.name", "users.email"],
            "filters": [
                {"field": "users.name", "operator": "CONTAINS", "value": "alice"},
                {
                    "field": "users.email",
                    "operator": "CONTAINS",
                    "value": "bob",
                    "combine_with_previous": "OR",
                },
            ],
            "joins": [],
            "aggregations": [],
            "group_by": [],
            "order_by": [],
            "limit": 10,
        },
        "sql_fragments": ["LOWER(users.name)", " OR ", "LOWER(users.email)"],
        "rows": [
            {"name": "Alice", "email": "alice@example.com"},
            {"name": "Bob", "email": "bob@example.com"},
        ],
        "row_count": 2,
    },
    {
        "name": "sort_by_name",
        "question": "show users ordered by name",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["users"],
            "fields": ["users.name"],
            "filters": [],
            "joins": [],
            "aggregations": [],
            "group_by": [],
            "order_by": [{"field": "users.name", "direction": "ASC"}],
            "limit": 10,
        },
        "sql_fragments": ["ORDER BY users.name ASC"],
        "rows": [{"name": "Alice"}, {"name": "Bob"}, {"name": "Charlie"}],
        "row_count": 3,
    },
    {
        "name": "latest_first_top_two",
        "question": "please show the latest two orders first",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["orders"],
            "fields": ["orders.id", "orders.amount", "orders.status"],
            "filters": [],
            "joins": [],
            "aggregations": [],
            "group_by": [],
            "order_by": [{"field": "orders.id", "direction": "DESC"}],
            "limit": 2,
        },
        "sql_fragments": ["ORDER BY orders.id DESC", "LIMIT 2"],
        "rows": [
            {"id": 4, "amount": 90.0, "status": "cancelled"},
            {"id": 3, "amount": 300.0, "status": "completed"},
        ],
        "row_count": 2,
    },
    {
        "name": "latest_first",
        "question": "show latest orders first",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["orders"],
            "fields": ["orders.id", "orders.amount", "orders.status"],
            "filters": [],
            "joins": [],
            "aggregations": [],
            "group_by": [],
            "order_by": [{"field": "orders.id", "direction": "DESC"}],
            "limit": 10,
        },
        "sql_fragments": ["ORDER BY orders.id DESC"],
        "rows": [
            {"id": 4, "amount": 90.0, "status": "cancelled"},
            {"id": 3, "amount": 300.0, "status": "completed"},
            {"id": 2, "amount": 60.0, "status": "pending"},
            {"id": 1, "amount": 120.5, "status": "completed"},
        ],
        "row_count": 4,
    },
    {
        "name": "join_projection",
        "question": "show order amounts with user names",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["orders", "users"],
            "fields": ["orders.amount", "users.name"],
            "filters": [],
            "joins": [{"left": "orders.user_id", "right": "users.id"}],
            "aggregations": [],
            "group_by": [],
            "order_by": [{"field": "orders.id", "direction": "ASC"}],
            "limit": 10,
        },
        "sql_fragments": ["JOIN users ON orders.user_id = users.id"],
        "rows": [
            {"amount": 120.5, "name": "Alice"},
            {"amount": 60.0, "name": "Bob"},
            {"amount": 300.0, "name": "Alice"},
            {"amount": 90.0, "name": "Charlie"},
        ],
        "row_count": 4,
    },
    {
        "name": "join_count_filter",
        "question": "how many orders where name is Alice",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["orders", "users"],
            "fields": [],
            "filters": [
                {"field": "users.name", "operator": "=", "value": "Alice"},
            ],
            "joins": [{"left": "orders.user_id", "right": "users.id"}],
            "aggregations": [{"function": "COUNT", "field": "*", "alias": "count"}],
            "group_by": [],
            "order_by": [],
            "limit": 10,
        },
        "sql_fragments": ["COUNT(*) AS count", "JOIN users ON orders.user_id = users.id"],
        "rows": [{"count": 2}],
        "row_count": 1,
    },
    {
        "name": "grouped_average",
        "question": "average order amount by user",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["orders", "users"],
            "fields": ["users.name"],
            "filters": [],
            "joins": [{"left": "orders.user_id", "right": "users.id"}],
            "aggregations": [{"function": "AVG", "field": "orders.amount", "alias": "avg_amount"}],
            "group_by": ["users.name"],
            "order_by": [{"field": "users.name", "direction": "ASC"}],
            "limit": 10,
        },
        "sql_fragments": ["AVG(orders.amount) AS avg_amount", "GROUP BY users.name"],
        "rows": [
            {"name": "Alice", "avg_amount": 210.25},
            {"name": "Bob", "avg_amount": 60.0},
            {"name": "Charlie", "avg_amount": 90.0},
        ],
        "row_count": 3,
    },
    {
        "name": "grouped_count",
        "question": "count orders per user",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["orders", "users"],
            "fields": ["users.name"],
            "filters": [],
            "joins": [{"left": "orders.user_id", "right": "users.id"}],
            "aggregations": [{"function": "COUNT", "field": "*", "alias": "count"}],
            "group_by": ["users.name"],
            "order_by": [{"field": "users.name", "direction": "ASC"}],
            "limit": 10,
        },
        "sql_fragments": ["COUNT(*) AS count", "GROUP BY users.name"],
        "rows": [
            {"name": "Alice", "count": 2},
            {"name": "Bob", "count": 1},
            {"name": "Charlie", "count": 1},
        ],
        "row_count": 3,
    },
    {
        "name": "grouped_count_verbose",
        "question": "for each user, tell me how many orders they have placed",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["orders", "users"],
            "fields": ["users.name"],
            "filters": [],
            "joins": [{"left": "orders.user_id", "right": "users.id"}],
            "aggregations": [{"function": "COUNT", "field": "*", "alias": "count"}],
            "group_by": ["users.name"],
            "order_by": [{"field": "users.name", "direction": "ASC"}],
            "limit": 10,
        },
        "sql_fragments": ["COUNT(*) AS count", "GROUP BY users.name"],
        "rows": [
            {"name": "Alice", "count": 2},
            {"name": "Bob", "count": 1},
            {"name": "Charlie", "count": 1},
        ],
        "row_count": 3,
    },
    {
        "name": "not_contains",
        "question": "show users where name does not contain ali",
        "backends": ["sqlite", "postgresql"],
        "expected": "success",
        "plan": {
            "tables": ["users"],
            "fields": ["users.name"],
            "filters": [
                {"field": "users.name", "operator": "NOT_CONTAINS", "value": "ali"},
            ],
            "joins": [],
            "aggregations": [],
            "group_by": [],
            "order_by": [{"field": "users.name", "direction": "ASC"}],
            "limit": 10,
        },
        "sql_fragments": ["NOT", "LIKE '%ali%'"],
        "rows": [{"name": "Bob"}, {"name": "Charlie"}],
        "row_count": 2,
    },
    {
        "name": "destructive_block",
        "question": "truncate the users table",
        "backends": ["sqlite", "postgresql"],
        "expected": "error",
        "plan": {"error": "Only read-only queries are allowed."},
    },
    {
        "name": "unsupported_median",
        "question": "show median order amount",
        "backends": ["sqlite", "postgresql"],
        "expected": "error",
        "plan": {"error": "Median aggregations are not supported yet."},
    },
]
